# 21-rulesets-firewall.conf
# Rulesets for firewall devices: Cisco ASA, Cisco FTD, FortiGate.

ruleset(name="rs_cisco_asa") {
    action(type="omfile"
           dynaFile="tpl_cisco_asa"
           template="StandardLogFormat"
           createDirs="on"
           dirCreateMode="0750"
           fileCreateMode="0640")
    stop
}

ruleset(name="rs_cisco_ftd") {
    action(type="omfile"
           dynaFile="tpl_cisco_ftd"
           template="StandardLogFormat"
           createDirs="on"
           dirCreateMode="0750"
           fileCreateMode="0640")
    stop
}

ruleset(name="rs_fortigate") {
    action(type="omfile"
           dynaFile="tpl_fortigate"
           template="StandardLogFormat"
           createDirs="on"
           dirCreateMode="0750"
           fileCreateMode="0640")
    stop
}
